package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;
    
    private JoinPredicate p;
    private DbIterator child1, child2;
    private TupleDesc td1, td2, tdJoin;
    private int field1, field2;
    private ArrayList<Tuple> childTups = new ArrayList<Tuple>();
    private Iterator<Tuple> it;

    /**
     * Constructor. Accepts to children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, DbIterator child1, DbIterator child2) {
        this.p = p;
        this.child1 = child1;
        this.child2 = child2;
        td1 = child1.getTupleDesc();
        td2 = child2.getTupleDesc();
        tdJoin = TupleDesc.merge(td1, td2);
        field1 = p.getField1();
        field2 = p.getField2();
    }

    public JoinPredicate getJoinPredicate() {
        return p;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        return td1.getFieldName(field1) + new Integer(1).toString();
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        return td2.getFieldName(field2) + new Integer(2).toString();
    }

    /**
     * @see simpledb.TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        return tdJoin;
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        child1.open();
        child2.open();
        // simple nested loop join
        while (child1.hasNext()) {
    		Tuple t1 = ((Tuple) child1.next());
    		while (child2.hasNext()) {
    			Tuple t2 = ((Tuple) child2.next());
    			if (p.filter(t1, t2)) {
    				Tuple tm = Tuple.merge(t1, t2);
    				childTups.add(tm);
    			}
    		}
    		child2.rewind();
    	}
        it = childTups.iterator();
        super.open();
    }

    public void close() {
        child1.close();
        child2.close();
        super.close();
        it = null;
    }

    public void rewind() throws DbException, TransactionAbortedException {
    	it = childTups.iterator();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        if (it != null && it.hasNext()) {
            return it.next();
        } else
            return null;
    }

    @Override
    public DbIterator[] getChildren() {
        return new DbIterator[] { this.child1, this.child2 };
    }

    @Override
    public void setChildren(DbIterator[] children) {
    	if (children[0] != null)
    		this.child1 = children[0];
    	if (children[1] != null)
    		this.child2 = children[1];
    }

}
